### ISSUE TITLE
目前最新版的skynet-mingw编译过后启动会崩溃.

### ISSUE THREAD

**Issue by korialuo** [dpull/skynet-mingw#10]
RT... 启动skynet提示缺少pthreadGC-3.dll
但从mingw目录复制pthreadGC-3.dll到skynet-mingw目录下过后, 启动skynet崩溃.

**Comment by dpull** [comment]
pthreadGC-3.dll 
libgcc_s_dw2-1.dll

这两个都是需要的，可以参考 https://github.com/dpull/skynet-mingw/blob/master/appveyor.yml  中的版本发布部分

**Comment by korialuo** [comment]
编译好后  需要的dll我都拷到相应目录了, 但是启动skynet还是会崩溃. 操作系统win7旗舰版

**Comment by dpull** [comment]
试验一下自动构建的版本：https://ci.appveyor.com/project/dpull/skynet-mingw/build/artifacts

**Comment by korialuo** [comment]
自动构建的版本没问题, 我自己再查查是哪里出了问题吧..

**Comment by dpull** [comment]
看看是不是mingw的问题，这儿用的mingw32

**Comment by 253627764** [comment]
我的也崩溃了

**Comment by dpull** [comment]
@korialuo  找到问题原因了吗？

**Comment by dpull** [comment]
我升级gcc到6.3后会出现clock_gettime 导致宕掉问题（https://github.com/dpull/skynet-mingw/issues/9），已经修复
