### ISSUE TITLE
win7 64位系统 旗舰版本 系统，编译通过，但是运行默认的config，提示找不到config.path

### ISSUE THREAD

**Issue by 253627764** [dpull/skynet-mingw#11]
$ ./skynet.exe  examples/config
**[skynet config]:17: .\config.path: No such file or directory**
按照 说明安装了相关的minigw工具，mingw-get-setup.exe  
版本是 **0.60222340.1**

**Comment by dpull** [comment]
dpull  18:21:26
你实验一下自动构建的版本
Felix.mao  18:51:17
自动构建怎么弄，就是你编译好的那个呀 
dpull  19:55:38
对
Felix.mao  20:31:42
自动构建的版本 是可以的
dpull  20:32:15
那你只能自查一下

**Comment by dpull** [comment]
package.config

一个描述有一些为包管理准备的编译期配置信息的串。 这个字符串由一系列行构成：

第一行是目录分割串。 对于 Windows 默认是 '\\' ，对于其它系统是 '/' 。


---------------------------------------------------------------------------------
skynet_main.c 中：
	local sep = package.config:sub(1,1)\n\
	local current_path = [[.]]..sep\n\
	local function include(filename)\n\
		local last_path = current_path\n\
		local path, name = filename:match([[(.*]]..sep..[[)(.*)$]])\n\

---------------------------------------------------------------------------------
所以需要使用'\' 的config路径

**Comment by dpull** [comment]
已经修改了readme的提示
