### ISSUE TITLE
make的时候error: unknown type name 'sigset_t'

### ISSUE THREAD

**Issue by scp096** [dpull/skynet-mingw#15]
platform/platform.h:16:2: error: unknown type name 'sigset_t'
  sigset_t sa_mask;
  ^
platform/platform.h:21:16: error: unknown type name 'sigset_t'
 int sigfillset(sigset_t *set);
                ^
platform/platform.h:22:17: error: unknown type name 'sigset_t'
 int sigemptyset(sigset_t *set);

**Comment by dpull** [comment]
什么环境  自动构建没有这问题

**Comment by scp096** [comment]
@dpull msys，按照你给的步骤来的，自动构建的我下载下来能跑，但有一个socket.lua的assertion failed的traceback
