### ISSUE TITLE
msys2编译，link函数重复

### ISSUE THREAD

**Issue by xiyoo0812** [dpull/skynet-mingw#16]
msys2编译，platform可以删掉一些代码，不过最后遇到一个问题，unistd.h和time.c有一个link函数重复定义了，不知道如何解决。

**Comment by dpull** [comment]
有没有判断是不是msys2的宏？

**Comment by xiyoo0812** [comment]
没找到msys1，在msys2下64位编译通过跑起来了，之前编译不过去掉unistd.h以及把EXTEND的函数声明去掉只保留实现就能编译过了。
底层库多了一些，platform可以省掉很多代码，现在只保留了pipe、read、write、close这4个EXTEND接口。
目前还有一个问题是socket.readline报错，有时间再看下。

**Comment by dpull** [comment]
提个pr？

**Comment by xiyoo0812** [comment]
提了，改动其实很小，只是升级了编译平台。你看下有没必要合吧！
