### ISSUE TITLE
自动编译版本无法运行测试

### ISSUE THREAD

**Issue by foreversos** [dpull/skynet-mingw#27]
![image](https://user-images.githubusercontent.com/3012313/183278865-19a7b130-2950-4d6d-9e12-bc869e984616.png)
似乎缺少文件或者路径不对?
![image](https://user-images.githubusercontent.com/3012313/183278875-6eaa64a4-5bf4-4a3b-8cce-3dad364895e2.png)

**Comment by dpull** [comment]
你安装个lua

**Comment by foreversos** [comment]
![image](https://user-images.githubusercontent.com/3012313/183339281-21c2e824-42ac-41f8-9d89-f6ffa5074dea.png)
谢谢回复,仍然不行....求助
@dpull

**Comment by dpull** [comment]
lua examples/client.lua
