### ISSUE TITLE
[skynet config]:17: .\config.path: No such file or directory

### ISSUE THREAD

**Issue by sdfwds4** [dpull/skynet-mingw#29]
从 https://ci.appveyor.com/project/dpull/skynet-mingw/build/artifacts 下载的1.0.557版本，没做任何修改，运行出错：
![image](https://github.com/dpull/skynet-mingw/assets/7692002/03267d84-75a8-470d-a544-c52a530da09c)

我的系统：
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2023/‎12/‎12
操作系统内部版本	19044.1682
体验	Windows Feature Experience Pack 120.2212.4170.0

**Comment by glfeng318** [comment]
update example/config
`include "config.path"` -> `include "examples/config.path"`

**Comment by dpull** [comment]
这是skynet那边的文件夹~~
