### ISSUE TITLE
关于windows版本的socket的error无法正常返回

### ISSUE THREAD

**Issue by heyilin416** [dpull/skynet-mingw#5]
由于socket_server.c的头文件包含顺序，winsock2.h定义SOCKET_ERROR=-1，而skynet定义是4，然后socket_server_poll处理时，如果是-1就直接continue掉了，造成windows版本socket的error就一直阻塞，通过将socket_server.h的包含调整到最下面可以解决此问题。

**Comment by dpull** [comment]
可否提交pr？

**Comment by dpull** [comment]
隔壁改了：https://github.com/cloudwu/skynet/issues/615

@cloudwu 👍
