### ISSUE TITLE
skynet_timer 中时间函数执行问题

### ISSUE THREAD

**Issue by ivan-kung** [dpull/skynet-mingw#9]
自己编译出来的版本，clock_gettime 执行时就挂掉，请问线上编译有出现这个问题吗，是如何处理的

**Comment by dpull** [comment]
没有特殊处理

你用自动构建的版本测试下

另外clock_gettime 这个函数在platform中，你可以单独摘出来试一下

**Comment by dpull** [comment]
请问结论如何 @vanishfan

**Comment by dpull** [comment]
我升级gcc到6.3后会出现这个问题，已经修复
